/*
Created by Conner Recoskie
May 15th, 2022
This program excepts the amount of Vrobits the user has and converts that value
to the 5 other coin types. The program also displays that amount of Vrobits left
needed to be able to convert to the higher up coin.  
*/

public class FrmZirboin extends javax.swing.JFrame {
    
    // Declaring double varibles for the diffrent coin types
    double vrobits = 0;
    double dropzits1 = 0;
    double clickwicks1 = 0;
    double gazoontights1 = 0;
    double frazoints1 = 0;
    double blointoints1 = 0;
    
    // Declaring double variables for the amount required sections
    double dropzitsRequired = 0;
    double clickwicksRequired = 0;
    double gazoontightsRequired = 0;
    double frazointsRequired = 0;
    double blointointsRequired = 0;
    
    /*
    toDropzits
    This method recives the vrobits value from the user and converts that value
    to dropzits by dividing it by 100000.
    Parameters: double
    Returns: double
    */
    public double toDropzits (double vrobits)
    {
        double dropzits;
        dropzits = vrobits/100000;
        return (dropzits);
    }
    
    /*
    toClickwicks
    This method recives the vrobits value from the user and converts that value
    to clickwicks by dividing it by 50000, it then returns it.
    Parameters: double
    Returns: double
    */
    public double toClickwicks (double vrobits)
    {
        double clickwicks;
        clickwicks = vrobits/50000;
        return (clickwicks);
    }
    
    /*
    toGazoontights
    This method recives the vrobits value from the user and converts that value
    to gazoontights by dividing it by 10000, it then returns it.
    Parameters: double
    Returns: double
    */
    public double toGazoontights (double vrobits)
    {
        double gazoontights;
        gazoontights = vrobits/10000;
        return (gazoontights);
    }
    
    /*
    toFrazoints
    This method recives the vrobits value from the user and converts that value
    to frazoints by dividing it by 1000, it then returns it.
    Parameters: double
    Returns: double
    */
    public double toFrazoints (double vrobits)
    {
        double frazoints;
        frazoints = vrobits/1000;
        return (frazoints);
    }
    
    /*
    toBlointoints
    This method recives the vrobits value from the user and converts that value
    to blointoints by dividing it by 500, it then returns it.
    Parameters: double
    Returns: double
    */
    public double toBlointoints (double vrobits)
    {
        double blointoints;
        blointoints = vrobits/500;
        return (blointoints);
    }

    
    public FrmZirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        txtVrobitsAmount = new javax.swing.JTextField();
        lblAmountDropzits = new javax.swing.JLabel();
        lblAmountClickwick = new javax.swing.JLabel();
        lblAmountGazoontights = new javax.swing.JLabel();
        lblAmountFrazoints = new javax.swing.JLabel();
        lblAmountBlointoints = new javax.swing.JLabel();
        lblAmountVrobits1 = new javax.swing.JLabel();
        lblAmountVrobits2 = new javax.swing.JLabel();
        lblAmountVrobits3 = new javax.swing.JLabel();
        lblAmountVrobits4 = new javax.swing.JLabel();
        lblAmountVrobits5 = new javax.swing.JLabel();
        lblDropzits = new javax.swing.JLabel();
        lblVrobits1 = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblVrobits2 = new javax.swing.JLabel();
        lblGazoontights = new javax.swing.JLabel();
        lblVrobits3 = new javax.swing.JLabel();
        lblFrazoints = new javax.swing.JLabel();
        lblVrobits4 = new javax.swing.JLabel();
        lblBlointoints = new javax.swing.JLabel();
        lblVrobits5 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        lblInstructions1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblTitle.setText("Zirboin Financial");

        lblInstructions.setForeground(new java.awt.Color(255, 51, 51));
        lblInstructions.setText("Please enter the amount of Vrobits you would like to exchange:");

        lblAmountDropzits.setText("Amount in Dropzits: ");

        lblAmountClickwick.setText("Amount in Clickwick:");

        lblAmountGazoontights.setText("Amount in Gazoontights: ");

        lblAmountFrazoints.setText("Amount in Frazoints:");

        lblAmountBlointoints.setText("Amount in Blointoints:");

        lblAmountVrobits1.setText("Left over Vrobits required:");

        lblAmountVrobits2.setText("Left over Vrobits required:");

        lblAmountVrobits3.setText("Left over Vrobits required:");

        lblAmountVrobits4.setText("Left over Vrobits required:");

        lblAmountVrobits5.setText("Left over Vrobits required:");

        lblDropzits.setText("0");

        lblClickwicks.setText("0");

        lblGazoontights.setText("0");

        lblFrazoints.setText("0");

        lblBlointoints.setText("0");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblInstructions1.setText("Enter how many Vrobits you have and click calculate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmountDropzits)
                            .addComponent(lblAmountVrobits1)
                            .addComponent(lblAmountClickwick)
                            .addComponent(lblAmountVrobits2)
                            .addComponent(lblAmountGazoontights)
                            .addComponent(lblAmountVrobits3)
                            .addComponent(lblAmountFrazoints)
                            .addComponent(lblAmountVrobits4)
                            .addComponent(lblAmountBlointoints)
                            .addComponent(lblAmountVrobits5)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblBlointoints, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFrazoints, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVrobits1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDropzits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVrobits2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClickwicks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGazoontights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVrobits3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVrobits4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVrobits5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInstructions1)
                            .addComponent(lblInstructions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVrobitsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructions1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstructions)
                    .addComponent(txtVrobitsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountDropzits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDropzits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountVrobits1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrobits1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAmountClickwick)
                    .addComponent(lblClickwicks, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountVrobits2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrobits2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountGazoontights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGazoontights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountVrobits3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrobits3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountFrazoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFrazoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountVrobits4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrobits4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountBlointoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBlointoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountVrobits5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrobits5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
    
    // Getting Vrobits value from user, stroring it in a variable
    vrobits = Double.parseDouble(txtVrobitsAmount.getText());

    /* Calling toDropzits method and passing it Vrobits value, storing the 
       result in a variable. */                              
    dropzits1 = toDropzits(vrobits);
    
    // Checking if the amount or vrobits meets the required amount for the coin
    if (vrobits < 100000)
    {   
        // Calculating how many vrobits short the person is for the coin 
        dropzitsRequired = vrobits - 100000;
        
        // Outputting how much more vrobits the user needs for the coin
        lblVrobits1.setText(String.valueOf("You need: " + 
                           Math.abs(dropzitsRequired) + " more Vrobits"));
    }
    else
    {   
        // Outputting the amount of coins they can exchange for, if they can
        lblDropzits.setText(String.valueOf(dropzits1));
    }

    /* Calling toClickwicks method and passing it Vrobits value, storing 
       the result in a variable */
    clickwicks1 = toClickwicks(vrobits);
    
    // Checking if the amount or vrobits meets the required amount for the coin
    if (vrobits < 50000)
    {
        // Calculating how many vrobits short the person is for the coin
        clickwicksRequired = clickwicks1 - 5000;
        
        // Outputting how much more vrobits the user needs for the coin
        lblVrobits2.setText(String.valueOf("You need: " + 
                           Math.abs(clickwicksRequired) + " more Vrobits"));
    }
    else
    {
        // Outputting the amount of coins they can exchange for, if they can
        lblClickwicks.setText(String.valueOf(clickwicks1));
    }

    /* Calling toGazoontights method and passing it Vrobits value, storing 
       the result in a variable */
    gazoontights1 = toGazoontights(vrobits);
    
    // Checking if the amount or vrobits meets the required amount for the coin
    if (vrobits < 10000)
    {
        // Calculating how many vrobits short the person is for the coin
        gazoontightsRequired = gazoontights1 - 10000;
        
        // Outputting how much more vrobits the user needs for the coin
        lblVrobits3.setText(String.valueOf("You need: "+ 
                           Math.abs(gazoontightsRequired) + " more Vrobits"));
    }
    else
    {
        // Outputting the amount of coins they can exchange for, if they can
        lblGazoontights.setText(String.valueOf(gazoontights1));
    }

    /* Calling toFrazoints method and passing it Vrobits value, storing 
       the result in a variable */
    frazoints1 = toFrazoints(vrobits);
    
    // Checking if the amount or vrobits meets the required amount for the coin
    if (vrobits < 1000)
    {
        // Calculating how many vrobits short the person is for the coin
        frazointsRequired = frazoints1 - 1000;
        
         // Outputting how much more vrobits the user needs for the coin
        lblVrobits4.setText(String.valueOf("You need: " + 
                           Math.abs(frazointsRequired) + " more Vrobits"));
    }
    else
    {
        // Outputting the amount of coins they can exchange for, if they can
        lblFrazoints.setText(String.valueOf(frazoints1));
    }

    /* Calling toBlointoints method and passing it Vrobits value, storing 
       the result in a variable */
    blointoints1 = toBlointoints(vrobits);

    // Checking if the amount or vrobits meets the required amount for the coin
    if (vrobits < 500)
    {
        // Calculating how many vrobits short the person is for the coin
        blointointsRequired = blointoints1 - 500;
        
        // Outputting how much more vrobits the user needs for the coin
        lblVrobits5.setText(String.valueOf("You need: " + 
                           Math.abs(blointointsRequired) + " more Vrobits"));
    }
    else
    {
        // Outputting the amount of coins they can exchange for, if they can
        lblBlointoints.setText(String.valueOf(blointoints1));
    }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmZirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblAmountBlointoints;
    private javax.swing.JLabel lblAmountClickwick;
    private javax.swing.JLabel lblAmountDropzits;
    private javax.swing.JLabel lblAmountFrazoints;
    private javax.swing.JLabel lblAmountGazoontights;
    private javax.swing.JLabel lblAmountVrobits1;
    private javax.swing.JLabel lblAmountVrobits2;
    private javax.swing.JLabel lblAmountVrobits3;
    private javax.swing.JLabel lblAmountVrobits4;
    private javax.swing.JLabel lblAmountVrobits5;
    private javax.swing.JLabel lblBlointoints;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblDropzits;
    private javax.swing.JLabel lblFrazoints;
    private javax.swing.JLabel lblGazoontights;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVrobits1;
    private javax.swing.JLabel lblVrobits2;
    private javax.swing.JLabel lblVrobits3;
    private javax.swing.JLabel lblVrobits4;
    private javax.swing.JLabel lblVrobits5;
    private javax.swing.JTextField txtVrobitsAmount;
    // End of variables declaration//GEN-END:variables
}
